#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" \

alias \
        cp="cp -iv" \
        mv="mv -iv" \
        rm="rm -vI" \
        bc="bc -ql" \
        mkd="mkdir -pv" \
        ls="ls -h --color=auto" \
        grep="grep --color=auto" \
        v="$EDITOR" \
        e="$EDITOR" \
        l="ls -alh" \
        venv="source .venv/bin/activate" \
        ytx="yt-x"

alias pip="pip3"
