#!bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

export EDITOR="nvim"
export TERMINAL="kitty"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export PLUGINS_HOME="$HOME/.local/share/zsh/plugins"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
