modmap:
  - name: main
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 150
  - name: HHKB
    remap:
      Ctrl_L:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 150
